feat: add path blacklist configuration
linuxdeepin/dde-grand-search pull request #12
Opened 2022-06-22 06:29 UTC by hanxiii-z

add path blacklist configuration in the setting interface

Log: users can add paths to the exclusion list to prevent searching in them

Task: https://pms.uniontech.com/task-view-110869.html
Change-Id: I5014d879557cc063b4822adac5447c2df832db34

2022-06-22 07:58 UTC, wangchunlin5013 commented on src/grand-search/gui/searchconfig/blacklistview/blacklistdelegate.h
> +
Invalid blank line

2022-06-22 07:58 UTC, wangchunlin5013 commented on src/grand-search/gui/searchconfig/blacklistview/blacklistmodel.h
> +
Invalid blank line

2022-06-22 07:58 UTC, wangchunlin5013 commented on src/grand-search/gui/searchconfig/blacklistwidget.cpp
> +
Invalid blank line

2022-06-22 11:29 UTC, Kakueeen approved these changes

2022-06-22 11:29 UTC, wangchunlin5013 submitted a review, later dismissed

2022-06-22 11:36 UTC, itsXuSt requested changes

2022-06-22 11:36 UTC, itsXuSt commented on src/grand-search/gui/searchconfig/blacklistview/blacklistview.h
> +#include<QVBoxLayout>
space

2022-06-22 11:36 UTC, itsXuSt commented on src/grand-search/gui/searchconfig/blacklistview/deletedialog.h
> +#include<DDialog>
space

2022-06-23 01:26 UTC, Kakueeen approved these changes

2022-06-23 05:18 UTC, Clauszy approved these changes

2022-06-23 05:18 UTC, merged