feat: add data burying point function
linuxdeepin/dde-grand-search pull request #24
Opened 2022-08-15 01:40 UTC by hanxiii-z

add start data burying point function

Log: if appliction is started, relevant data will be collected.

Task: https://pms.uniontech.com/task-view-173243.html

2022-08-16 03:19 UTC, wangchunlin5013 commented on src/buryingpoint/datafactory.cpp
> +{
BaseData *p = nullptr;

2022-08-16 03:20 UTC, wangchunlin5013 commented on src/buryingpoint/datafactory.cpp
> +        StartData *p = new StartData();
每个分支，直接赋值后break出去，在switch外面一条return语句即可

2022-08-16 03:21 UTC, wangchunlin5013 commented on src/buryingpoint/datafactory.h
> +    explicit DataFactory();
public 的构造函数，意味者用户可以任意创建该工厂对象

2022-08-16 05:29 UTC, Clauszy requested changes

2022-08-16 05:29 UTC, Clauszy commented on CMakeLists.txt
> +    "./src/buryingpoint/*.h" "./src/buryingpoint/*.cpp"
使用专门的分组放埋点
GLOB BURYINGPOINT_SRC

2022-08-16 05:29 UTC, Clauszy commented on src/buryingpoint/basedata.cpp
> +void BaseData::addData(const QVariantMap &data)
addData？
接口名称与实现不符

2022-08-16 05:29 UTC, Clauszy commented on src/buryingpoint/basedata.h
> +enum EventId {
注释

2022-08-16 05:29 UTC, Clauszy commented on src/buryingpoint/eventlogutil/eventlogutil.cpp
> +    init =reinterpret_cast<bool (*)(const std::string &, bool)>(library.resolve("Initialize"));
space

2022-08-16 06:12 UTC, wangchunlin5013 commented on src/buryingpoint/basedata.cpp
> +using namespace GrandSearch;
头文件使用using namespace容易照成命令空间污染

2022-08-16 06:21 UTC, wangchunlin5013 commented on src/buryingpoint/basedata.h
> +private:
protected

2022-08-16 06:21 UTC, wangchunlin5013 commented on src/buryingpoint/startdata.h
> +    QPair<QString, EventId> m_eventId;
删除

2022-08-16 06:25 UTC, wangchunlin5013 requested changes

2022-08-16 06:25 UTC, wangchunlin5013 commented on src/grand-search/main.cpp
> +            GrandSearch::BaseData *p = GrandSearch::DataFactory::instance()->createData(GrandSearch::EventId::Start);
可以考虑用QScopedPointer

2022-08-17 01:24 UTC, Clauszy requested changes

2022-08-17 01:24 UTC, Clauszy commented on src/buryingpoint/datafactory.h
> +class DataFactory
类名太泛指了，需明确是埋点的工厂

2022-08-17 01:24 UTC, Clauszy commented on src/buryingpoint/datafactory.cpp
> +    switch (id){
space

2022-08-17 01:24 UTC, Clauszy commented on src/buryingpoint/datafactory.cpp
> +        p = new StartData();
类名需要修改

2022-08-17 01:24 UTC, Clauszy commented on src/buryingpoint/basedata.h
> +class BaseData
基类名称太泛指了

2022-08-17 01:24 UTC, Clauszy commented on src/buryingpoint/basedata.h
> +enum EventId {
过于泛指的定义

2022-08-17 01:41 UTC, wangchunlin5013 requested changes

2022-08-17 01:41 UTC, wangchunlin5013 commented on src/buryingpoint/startdata.h
> +//    QPair<QString, EventId> m_eventId;
意义何在？为啥不删除？保留的目的是什么？注释了请说明原因！

2022-08-17 06:25 UTC, wangchunlin5013 submitted a review, later dismissed

2022-08-17 06:39 UTC, Clauszy approved these changes

2022-08-17 06:40 UTC, hanxiii-z commented
/merge

2022-08-17 07:17 UTC, wangchunlin5013 approved these changes

2022-08-17 07:26 UTC, Clauszy approved these changes

2022-08-17 07:26 UTC, hanxiii-z commented
/merge

2022-08-17 07:26 UTC, merged