chore: adap REUSE license
linuxdeepin/dde-grand-search pull request #39
Opened 2022-10-24 07:42 UTC by tingwei1123

Distinguish between self-developed code and non-self-developed code
Log: Distinguish between self-developed code and non-self-developed code

2022-10-24 09:20 UTC, Clauszy requested changes

2022-10-24 09:20 UTC, Clauszy commented on src/grand-search/CMakeLists.txt
> +set(3RDPARTY
DBUSSRC

2022-10-24 09:20 UTC, Clauszy commented on src/grand-search/CMakeLists.txt
> +    ${CMAKE_SOURCE_DIR}/3rdparty/interfaces/daemongrandsearchinterface.h
在根cmake中定义${CMAKE_SOURCE_DIR}/3rdparty/， 这里太长了

2022-10-24 09:20 UTC, Clauszy commented on src/grand-search/main.cpp
> +#include "services/grandsearchserviceadaptor.h"
分块，下移

2022-10-26 01:49 UTC, Clauszy approved these changes

2022-10-26 02:02 UTC, tingwei1123 commented
-merge

2022-10-27 07:44 UTC, tingwei1123 commented
/merge

2022-10-27 07:44 UTC, merged