fix: dbus cannot monitor the signal that VisibleChanged is true
linuxdeepin/dde-grand-search pull request #99
Opened 2024-07-04 10:19 UTC by yixinshark

delay emit mainwindow‘s visible changed signal

Log: as title
Influence: can get VisibleChanged is true signal

2024-07-05 09:22 UTC, 18202781743 approved these changes

2024-07-08 09:19 UTC, Clauszy requested changes

2024-07-08 09:19 UTC, Clauszy commented on src/grand-search/gui/mainwindow.cpp
> +        emit visibleChanged(true);
QMetaObject::invokeMethod(this, "visibleChanged", Qt::QueuedConnection, Q_ARG(bool, true));

2024-07-08 09:24 UTC, yixinshark commented on src/grand-search/gui/mainwindow.cpp
> +        emit visibleChanged(true);
换了个写法。对信号来说使用invokeMethod，不直观，虽然也是函数。建议使用singleShot 0,lamda函数更直观。

已按上述说的修改。

2024-07-08 10:05 UTC, Clauszy approved these changes

2024-07-08 10:06 UTC, yixinshark commented
/merge

2024-07-08 10:06 UTC, merged